services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
      POSTGRES_DB: antipatterns
    volumes:
      - dbVolume:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  dbVolume:
    driver: local
