services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: detector
      POSTGRES_USER: root
      POSTGRES_DB: antipatternDetector
    volumes:
      - dbVolume:/var/lib/postgresql/data
    ports:
      - 5431:5432
volumes:
  dbVolume:
    driver: local
